package report

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestMarkdownReporter_GenerateReport_Content(
	t *testing.T,
) {
	r := NewMarkdownReporter(t.TempDir())
	result := makeTestResult()

	data, err := r.GenerateReport(result)
	require.NoError(t, err)

	content := string(data)
	assert.Contains(t, content, "# Challenge Report:")
	assert.Contains(t, content, "Test Challenge")
	assert.Contains(t, content, "test-001")
	assert.Contains(t, content, "PASSED")
	assert.Contains(t, content, "## Metrics")
	assert.Contains(t, content, "latency")
	assert.Contains(t, content, "120.50")
	assert.Contains(t, content, "## Assertions")
	assert.Contains(t, content, "1/2 (50%)")
	assert.Contains(t, content, "## Output Files")
	assert.Contains(t, content, "## Log Files")
	assert.Contains(t, content, "Challenges Framework")
	assert.NotContains(t, content, "HelixAgent")
}

func TestMarkdownReporter_GenerateReport_NoMetrics(
	t *testing.T,
) {
	r := NewMarkdownReporter(t.TempDir())
	result := makeTestResult()
	result.Metrics = nil

	data, err := r.GenerateReport(result)
	require.NoError(t, err)
	assert.NotContains(t, string(data), "## Metrics")
}

func TestMarkdownReporter_GenerateReport_WithError(
	t *testing.T,
) {
	r := NewMarkdownReporter(t.TempDir())
	result := makeTestResult()
	result.Status = "failed"
	result.Error = "something broke"

	data, err := r.GenerateReport(result)
	require.NoError(t, err)
	assert.Contains(t, string(data), "something broke")
}

func TestMarkdownReporter_WriteReport(t *testing.T) {
	r := NewMarkdownReporter(t.TempDir())
	result := makeTestResult()

	var buf bytes.Buffer
	err := r.WriteReport(&buf, result)
	require.NoError(t, err)
	assert.True(t, strings.HasPrefix(buf.String(), "#"))
}

func TestMarkdownReporter_GenerateMasterSummary_Content(
	t *testing.T,
) {
	r := NewMarkdownReporter(t.TempDir())
	results := makeTestResults()

	data, err := r.GenerateMasterSummary(results)
	require.NoError(t, err)

	content := string(data)
	assert.Contains(
		t, content, "Challenges Framework - Master Summary",
	)
	assert.Contains(t, content, "Test Challenge")
	assert.Contains(t, content, "Another Challenge")
	assert.Contains(t, content, "## Statistics")
	assert.Contains(t, content, "Total Challenges")
	assert.Contains(t, content, "50%")
	assert.Contains(
		t, content, "Generated by Challenges Framework",
	)
}

func TestMarkdownReporter_SaveReport(t *testing.T) {
	dir := t.TempDir()
	r := NewMarkdownReporter(dir)
	result := makeTestResult()

	err := r.SaveReport(result, "report.md")
	require.NoError(t, err)

	path := filepath.Join(dir, "report.md")
	data, err := os.ReadFile(path)
	require.NoError(t, err)
	assert.Contains(t, string(data), "Test Challenge")
}

func TestMarkdownReporter_SaveMasterSummary(t *testing.T) {
	dir := t.TempDir()
	r := NewMarkdownReporter(dir)
	results := makeTestResults()

	err := r.SaveMasterSummary(results, "summary.md")
	require.NoError(t, err)

	path := filepath.Join(dir, "summary.md")
	data, err := os.ReadFile(path)
	require.NoError(t, err)
	assert.Contains(t, string(data), "Master Summary")
}
